In [2]:
from deepmol.pipeline import Pipeline

pipeline = Pipeline.load("hia/hia/trial_36")

2024-01-16 13:25:35.097223: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-16 13:25:35.141645: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-16 13:25:35.141685: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-16 13:25:35.141730: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-16 13:25:35.150890: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-16 13:25:35.151673: I tensorflow/core/platform/cpu_feature_guard.cc:182] This Tens

In [3]:
from deepmol.datasets import SmilesDataset

dataset = SmilesDataset(smiles=["CC(=O)OC1=CC=CC=C1C(=O)O", "CC(=O)NC1=CC=C(C=C1)O"], mode="classification")
pipeline.predict(dataset)

array([1, 1])

In [4]:
pipeline = Pipeline.load("hia/hia/trial_55")

/home/jcapela/miniforge3/envs/deepmol_new_version/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2024-01-16 13:25:48.614701: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2211] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [5]:
pipeline = Pipeline.load("hia/hia/trial_65")
pipeline = Pipeline.load("hia/hia/trial_89")

In [6]:
from deepmol.pipeline import VotingPipeline

pipeline = VotingPipeline.load("hia/hia/voting_pipeline")

In [7]:
from deepmol.datasets import SmilesDataset

dataset = SmilesDataset(smiles=["CC(=O)OC1=CC=CC=C1C(=O)O", "CC(=O)NC1=CC=C(C=C1)O"], mode="classification")
pipeline.predict_proba(dataset)

array([[6.77225902e-04, 9.99322760e-01],
       [1.01814934e-06, 9.99998975e-01]])

In [9]:
import numpy as np

test_array = np.array([[[9.99322784e-01, 6.77239895e-04],
  [6.77225902e-04, 9.99322760e-01]],
 [[9.99998987e-01, 1.02519989e-06],
  [1.01814934e-06, 9.99998975e-01]]])

In [10]:
1 - np.array([9.99322784e-01, 6.77239895e-04])

array([6.7721600e-04, 9.9932276e-01])

In [8]:
np.argmax(test_array, axis=0)

array([[1, 0],
       [0, 1]])

In [3]:
pipeline.predict_proba(dataset)

array([[6.77225902e-04, 9.99322760e-01],
       [1.01814934e-06, 9.99998975e-01]])